coherence-spring-core/src/main/java/com/oracle/coherence/spring/configuration/DefaultCoherenceConfigurer.java

Fix compilation issue due to Coherence bootstrap API changes

Fix compilation issue due to Coherence bootstrap API changes

---

coherence-spring-boot-starter/pom.xml
coherence-spring-docs/src/main/asciidoc/attributes.adoc
coherence-spring-docs/src/main/asciidoc/spring-boot.adoc
pom.xml
samples/hibernate-cache-demo/pom.xml
samples/hibernate-cache-demo/src/main/java/com/oracle/coherence/spring/samples/hibernate/HibernateApplication.java
samples/hibernate-cache-demo/src/main/java/com/oracle/coherence/spring/samples/hibernate/controller/PlantController.java
samples/hibernate-cache-demo/src/main/java/com/oracle/coherence/spring/samples/hibernate/controller/package-info.java
samples/hibernate-cache-demo/src/main/java/com/oracle/coherence/spring/samples/hibernate/dao/PlantRepository.java
samples/hibernate-cache-demo/src/main/java/com/oracle/coherence/spring/samples/hibernate/dao/package-info.java
samples/hibernate-cache-demo/src/main/java/com/oracle/coherence/spring/samples/hibernate/model/Plant.java
samples/hibernate-cache-demo/src/main/java/com/oracle/coherence/spring/samples/hibernate/model/package-info.java
samples/hibernate-cache-demo/src/main/java/com/oracle/coherence/spring/samples/hibernate/package-info.java
samples/hibernate-cache-demo/src/main/resources/application.yaml
samples/hibernate-cache-demo/src/test/java/com/oracle/coherence/spring/samples/hibernate/HibernateApplicationTests.java
samples/pom.xml
samples/spring-session-demo/spring-session-demo-app/src/main/java/com/oracle/coherence/spring/samples/session/config/package-info.java
samples/spring-session-demo/spring-session-demo-app/src/main/java/com/oracle/coherence/spring/samples/session/controller/package-info.java
samples/spring-session-demo/spring-session-demo-app/src/main/java/com/oracle/coherence/spring/samples/session/filter/package-info.java
samples/spring-session-demo/spring-session-demo-server/src/main/java/com/oracle/coherence/spring/samples/session/package-info.java
src/main/config/dependency-check-suppression.xml

gh-54 Add Sample and Docs for using Hibernate's Second Level Cache with Spring Boot

---

coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/CoherenceAutoConfiguration.java
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/CoherenceProperties.java
coherence-spring-boot-starter/src/test/java/com/oracle/coherence/spring/boot/tests/CoherencePropertiesTests.java
coherence-spring-boot-starter/src/test/java/com/oracle/coherence/spring/boot/tests/cache/CacheAbstractionWithPrefixTests.java
coherence-spring-boot-starter/src/test/resources/application-coherenceCacheTestsWithPrefix.yaml
coherence-spring-core/src/main/java/com/oracle/coherence/spring/cache/CoherenceCacheConfiguration.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/cache/CoherenceCacheManager.java

gh-60 Spring Cache: Add Ability to set cache prefix

---

coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/session/CoherenceSpringSessionAutoConfiguration.java
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/session/CoherenceSpringSessionCondition.java
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/session/CoherenceSpringSessionProperties.java
coherence-spring-boot-starter/src/main/resources/META-INF/spring.factories
coherence-spring-boot-starter/src/test/java/com/oracle/coherence/spring/boot/tests/CoherenceSpringSessionAutoConfigurationTests.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/configuration/EnableCoherenceImportBeanDefinitionRegistrar.java
coherence-spring-docs/src/main/asciidoc/spring-boot.adoc
coherence-spring-session/src/main/java/com/oracle/coherence/spring/session/config/annotation/web/http/CoherenceHttpSessionConfiguration.java
samples/coherence-spring-demo/coherence-spring-demo-boot/src/main/resources/application.yml

gh-61 Spring Session: Activate Spring Session auto-configuration support solely by adding the dependency

---

coherence-spring-boot-starter/pom.xml
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/data/CoherenceRepositoriesAutoConfiguration.java
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/data/CoherenceRepositoriesRegistrar.java
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/data/package-info.java
coherence-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
coherence-spring-boot-starter/src/main/resources/META-INF/spring.factories
coherence-spring-boot-starter/src/test/java/com/oracle/coherence/spring/boot/tests/data/SpringDataAutoConfigurationTests.java
coherence-spring-docs/src/main/asciidoc/spring-boot.adoc

gh-58 Add auto-configuration support for Spring Data

---

coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/CoherenceAutoConfiguration.java
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/CoherenceProperties.java
coherence-spring-boot-starter/src/test/java/com/oracle/coherence/spring/boot/tests/CoherencePropertiesTests.java
coherence-spring-boot-starter/src/test/resources/application-coherencePropertiesTests.yaml
coherence-spring-core/pom.xml
coherence-spring-core/src/main/java/com/oracle/coherence/spring/CoherenceServer.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/configuration/CoherenceSpringConfiguration.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/configuration/DefaultCoherenceConfigurer.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/configuration/session/AbstractSessionConfigurationBean.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/configuration/session/ClientSessionConfigurationBean.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/configuration/session/ServerSessionConfigurationBean.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/configuration/support/CoherenceConfigurerCustomizer.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/configuration/support/CoherenceInstanceType.java
coherence-spring-session/pom.xml
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/AbstractCoherenceIndexedSessionRepositoryTests.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/ExtendSessionCoherenceIndexedSessionRepositoryTests.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/GrpcSessionCoherenceIndexedSessionRepositoryTests.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/PofCoherenceIndexedSessionRepositoryTests.java
coherence-spring-session/src/test/resources/client-coherence-cache-config.xml
coherence-spring-session/src/test/resources/server-coherence-cache-config.xml
coherence-spring-tests/pom.xml
coherence-spring-tests/src/main/java/com/oracle/coherence/spring/test/junit/CoherenceServerJunitExtension.java
pom.xml

- Also, add ability to specify the Coherence server startup timeout via a Spring Boot property
resolves #71

gh-71 Make the Coherence instance type configurable

---

coherence-spring-boot-starter/src/test/java/com/oracle/coherence/spring/boot/tests/CoherenceAutoConfigurationTests.java
coherence-spring-core/src/main/java/com/oracle/coherence/spring/CoherenceServer.java
coherence-spring-docs/src/main/asciidoc/spring-boot.adoc

gh-79 Increase the default Coherence startup timeout to 5 minutes

---

pom.xml
samples/coherence-spring-cloud-config-demo/pom.xml

- Update to Spring Boot `2.6.4`
- Update Spring Cloud dependency of the `coherence-spring-cloud-config-demo` to `2021.0.1`
Resolves #92

Update to Spring Boot 2.6.4

---

.mvn/wrapper/maven-wrapper.properties
pom.xml
samples/coherence-spring-demo/coherence-spring-demo-classic/pom.xml
samples/coherence-spring-demo/coherence-spring-demo-core/pom.xml
src/main/config/dependency-check-suppression.xml

- Clean up dependency check supressions + update minor dependency versions
- Update dependency-check-maven from `6.5.3` to `7.0.4`
- Update nexus-staging-maven-plugin version from `1.6.8` to `1.6.12`
- Update Spring Session version from `2.6.1` to `2.6.2`
- Update Spring Security version from `5.5.4` to `5.5.5`
- Update Tomcat version from `9.0.58` to `9.0.62`
- Update Maven wrapper version from `3.8.2` to `3.8.5`
Resolves #94

Polish update to Spring Boot 2.6.6

---

.github/workflows/maven.yml
coherence-spring-data/src/test/java/com/oracle/coherence/spring/data/AbstractDataTest.java
coherence-spring-data/src/test/java/com/oracle/coherence/spring/data/model/Book.java
coherence-spring-data/src/test/java/com/oracle/coherence/spring/data/model/PublicationYearClassProjection.java
coherence-spring-data/src/test/java/com/oracle/coherence/spring/data/model/repositories/BookProjectionRepository.java
coherence-spring-data/src/test/java/com/oracle/coherence/spring/data/repository/ProjectionTest.java
pom.xml
samples/coherence-spring-demo/coherence-spring-demo-classic/pom.xml

gh-101 Ensure Compatibility with Java 17

---

coherence-spring-boot-starter/src/test/java/com/oracle/coherence/spring/boot/tests/CoherenceAutoConfigurationTests.java

Add test to verify backing-off in case of existing non-Coherence CacheManager bean

---

coherence-spring-core/src/test/java/com/oracle/coherence/spring/configuration/CoherenceNamedCacheConfigurationNamedMapTests.java
coherence-spring-core/src/test/java/com/oracle/coherence/spring/configuration/CoherenceNamedCacheConfigurationTests.java
coherence-spring-core/src/test/java/com/oracle/coherence/spring/messaging/CoherenceTopicListenerTest.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/GrpcSessionCoherenceIndexedSessionRepositoryTests.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/PofCoherenceIndexedSessionRepositoryTests.java
coherence-spring-tests/src/main/java/com/oracle/coherence/spring/test/junit/CoherenceServerJunitExtension.java
pom.xml

Upgrade Coherence to 22.06.2

---

coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/CoherenceAutoConfiguration.java
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/data/CoherenceRepositoriesAutoConfiguration.java
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/metrics/CoherenceMetricsAutoConfiguration.java
coherence-spring-boot-starter/src/main/java/com/oracle/coherence/spring/boot/autoconfigure/session/CoherenceSpringSessionAutoConfiguration.java
coherence-spring-boot-starter/src/main/resources/META-INF/spring.factories
coherence-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
coherence-spring-boot-starter/src/test/java/com/oracle/coherence/spring/boot/tests/CoherenceSpringFactoryTests.java
pom.xml

Revert "Migrate to new AutoConfiguration support in Boot 2.7"

---

pom.xml

gh-146 Upgrade Spring Boot dependency to 3.1.1

---

pom.xml
src/main/config/dependency-check-suppression.xml

gh-151 Suppress invalid CVE report for Jackson Databind

---

.github/workflows/ci-pr.yml
coherence-spring-core/src/test/java/com/oracle/coherence/spring/session/GrpcSessionBeanTests.java
coherence-spring-core/src/test/java/com/oracle/coherence/spring/session/GrpcSessionTests.java
pom.xml

gh-149 Add CI process for pull requests

---

coherence-spring-docs/src/main/asciidoc/attributes.adoc
coherence-spring-docs/src/main/asciidoc/spring-boot.adoc

Fix link in docs to Circuit Breaker example

---

coherence-spring-docs/src/main/asciidoc/core.adoc

gh-120 Fix typo in CacheStore reference chapter

---

README.adoc
coherence-spring-site/docs/dev/03_build-instructions.adoc

gh-107 Remove the `spring` Maven profile from the documentation

---

coherence-spring-core/src/test/java/com/oracle/coherence/spring/session/GrpcSessionBeanTests.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/GrpcSessionCoherenceIndexedSessionRepositoryTests.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/PofCoherenceIndexedSessionRepositoryTests.java
pom.xml

gh-169 Upgrade Coherence dependency to 23.03.1

---

coherence-spring-docs/src/main/asciidoc/spring-boot.adoc
pom.xml
samples/circuit-breaker-cache-demo/README.adoc
samples/circuit-breaker-cache-demo/circuit-breaker-cache-demo-app/pom.xml

gh-179 Update Resilience4j Sample for Spring Boot 3

---

coherence-spring-docs/src/main/asciidoc/core.adoc

gh-181 Add Chapter on Injecting Spring Beans into Coherence-Managed objects

---

coherence-spring-boot-starter/pom.xml
coherence-spring-boot-starter/src/test/java/com/oracle/coherence/spring/boot/config/CoherenceConfigDataLoaderTests.java

gh-217 Convert CoherenceConfigDataLoaderTests to use Bedrock

---

coherence-spring-docs/src/main/asciidoc/appendix-examples.adoc
coherence-spring-docs/src/main/asciidoc/appendix.adoc
coherence-spring-docs/src/main/asciidoc/coherence-spring-reference.pdfadoc
coherence-spring-docs/src/main/asciidoc/index.htmladoc
coherence-spring-docs/src/main/asciidoc/index.htmlsingleadoc

gh-240 Doc: Provide an appendix that lists all known Coherence Spring Examples/Demos

---

coherence-spring-docs/src/main/asciidoc/spring-session.adoc

gh-357 Spring Session: Document different ways to specify the session timeouts

---

coherence-spring-session/src/main/java/com/oracle/coherence/spring/session/CoherenceIndexedSessionRepository.java
coherence-spring-session/src/main/java/com/oracle/coherence/spring/session/config/annotation/web/http/CoherenceHttpSessionConfiguration.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/CustomSessionIdGeneratorTests.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/support/FixedSessionIdGenerator.java

Make sessionIdGenerator configurable

---

coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/AbstractCoherenceIndexedSessionRepositoryTests.java
coherence-spring-session/src/test/java/com/oracle/coherence/spring/session/support/MyHttpSessionListener.java

Added additional logging to aid diagnosing failures in this test case.

Small modification to listener reset.

---

pom.xml

Update distributionManagement for sonatype central deployment

Update distributionManagement for sonatype central deployment

---

pom.xml

This reverts commit c3ae74be806d22e5c877d81f42c42ef51e4c829a.

Revert "Bump io.spring.javaformat:spring-javaformat-checkstyle"
